services:
  app:
    container_name: myapp
    build:
      dockerfile: Dockerfile
      context: .

    ports:
      - 443:443
      - 80:80

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /nginx.conf:/etc/nginx/conf.d/default.conf:ro
